# Generated by Django 3.0.6 on 2020-05-25 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='static/images/movies')),
                ('title', models.CharField(max_length=200)),
                ('publish_year', models.DateTimeField()),
                ('comment', models.TextField(null=True)),
                ('genre', models.CharField(max_length=100)),
                ('point', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='static/images/people')),
                ('full_name', models.CharField(max_length=300)),
                ('birth_date', models.DateTimeField()),
                ('birth_place', models.CharField(max_length=300, null=True)),
                ('comment', models.TextField(null=True)),
                ('point', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='static/images/series')),
                ('title', models.CharField(max_length=200)),
                ('start_year', models.DateTimeField()),
                ('end_year', models.DateTimeField()),
                ('comment', models.TextField(null=True)),
                ('genre', models.CharField(max_length=100)),
                ('point', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.People')),
                ('serial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Series')),
            ],
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images/cinemas')),
                ('name', models.CharField(max_length=300)),
                ('establish_date', models.DateTimeField()),
                ('address', models.TextField(null=True)),
                ('point', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('movie', models.ManyToManyField(to='main.Movie')),
            ],
        ),
    ]
