# Generated by Django 3.0.6 on 2020-07-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200718_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='type_of_product',
            field=models.CharField(choices=[('M', 'Movie'), ('S', 'Serial')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='type_of_role',
            field=models.CharField(choices=[('A', 'Actor'), ('D', 'Director'), ('W', 'Writer')], max_length=1, null=True),
        ),
    ]
