# Generated by Django 3.0.6 on 2020-07-30 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200722_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_form',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='contact_form',
            name='last_name',
        ),
    ]
