# Generated by Django 3.0.6 on 2020-08-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200730_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='latitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cinema',
            name='longitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='establish_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='publish_year',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='birth_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='end_year',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='start_year',
            field=models.DateTimeField(null=True),
        ),
    ]
